export const internalRoutes = {
  home: "/",
  SinglePackage: "/package",
  searchresultPage: "/search",
  wishlist: "/wishlist",
  checkout: "/checkout",
  payment: "/checkout/payment",
  orderStatus: "/orderStatus",
  interest: "/select-your-interest",
  profile: "/user/profile",
  order: "/user/order",
  orderDetail: "/user/order/detail",
  bookingForm: "/booking-form",
  thankyou: "/thank-you",
  ourServices: "/services",

  userSignup: "/user/signup",
  userLogin: "/user/login",
  userDashboard: "/user/dashboard",
  userForgotPassword: "/user/forgot-password",
  adminSignup: "/admin/signup",
  adminLogin: "/admin/login",
  adminDashboard: "/admin/dashboard",

  vendorSignup: "/vendor/signup",
  vendorLogin: "/vendor/login",
  vendorForgotPassword: "/vendor/forgot-password",

  vendorDashboard: "/vendor/dashboard",
  vendorProfile: "/vendor/profile",
  vendorServices: "/vendor/services",
  vendorOrders: "/vendor/orders",
  vendorOrderDeatil: "/vendor/orders/vendorOrderDeatil",
  vendorSupport: "/vendor/support",
  vendorCommunity: "/vendor/community",
  vendorCreateservice: "/vendor/Createservice",
  vendorEditservice: "/vendor/Editservice",

  aboutUs: "/about-us",
  careers: "/careers",
  blog: "/blogs",
  singleBlog: "/blogs/singleBlog",
  pressReleases: "/press-releases",
  advertiseWithUs: "/advertise-with-us",
  grievanceOfficer: "/grievance-officer",
  popularSearches: "/popular-searches",
  evagaCommunity: "/evaga-community",
  becomeAVendor: "/become-a-vendor",
  vendorOnboarding: "/vendor-onboarding",
  cancellationPolicy: "/cancellation-policy",
  TermsAndConditions: "/terms-and-condition",
  privacyAndPolicy: "/privacy-policy",
  feedbackForm: "/feedback-form",
  customerService: "/customer-service",
};
